In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [2]:
df=pd.read_csv('IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words --> words like and, is, the, from, etc.
6. Stemming --> for eg. play, playing, played will be one word called play

In [5]:
df=df.sample(10000)

In [6]:
df.shape

(10000, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 24045 to 18858
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [8]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

C:\Users\Ronit\AppData\Local\Temp\ipykernel_8844\4240984564.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)
C:\Users\Ronit\AppData\Local\Temp\ipykernel_8844\4240984564.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [9]:
df.head()

                                                  review  sentiment
24045  This is according to me a quite bizarre movie ...          1
6619   All the people who voted a meager 1 on this mo...          1
21179  Written by Stephen King, but this treatment is...          0
5611   I have no idea what the producers of The Shiel...          0
14729  I saw this film awhile back (while working on ...          0

In [10]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'Written by Stephen King, but this treatment is not as solid as most of his stories on film. A mother and son move into a small Indiana town with a secret. They are Sleepwalkers, feline type creatures that feed on young virgins. This little story has its share of gore and special effects; plus hints of incest.Alice Krige is outstanding as the mother. Others appearing are Madchen Amick, Brian Krause and Cindy Pickett. Look for very small roles for John Landis and Clive Barker. Stephen King cameos as the caretaker of the cemetery.'

In [11]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [12]:
df['review']=df['review'].apply(clean_html)

In [13]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [14]:
df['review']=df['review'].apply(convert_lower)

In [15]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [16]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [17]:
df['review']=df['review'].apply(remove_special)

In [18]:
# Remove the stop words
#nltk --> natural language toolkit used in nlp
import nltk

In [19]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ronit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
from nltk.corpus import stopwords

In [21]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [22]:
df

                                                  review  sentiment
24045  this is according to me a quite bizarre movie ...          1
6619   all the people who voted a meager 1 on this mo...          1
21179  written by stephen king  but this treatment is...          0
5611   i have no idea what the producers of the shiel...          0
14729  i saw this film awhile back  while working on ...          0
...                                                  ...        ...
39536  this show is like watching someone who is in t...          0
15903  this is not a children s movie   this movie is...          0
27413   tumbling doll of flesh  by tamakichi anaru is...          1
710    director don siegel really impressed me with t...          1
18858  gabe ryan  frankie thomas  gets out of reform ...          1

[10000 rows x 2 columns]

In [23]:

def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [24]:
df['review']=df['review'].apply(remove_stopwords)

In [25]:
df

                                                  review  sentiment
24045  [according, quite, bizarre, movie, lot, humor,...          1
6619   [people, voted, meager, 1, movie, say, guys, m...          1
21179  [written, stephen, king, treatment, solid, sto...          0
5611   [idea, producers, shield, trying, result, spea...          0
14729  [saw, film, awhile, back, working, trailer, fi...          0
...                                                  ...        ...
39536  [show, like, watching, someone, training, some...          0
15903  [children, movie, movie, like, bad, acid, trip...          0
27413  [tumbling, doll, flesh, tamakichi, anaru, japa...          1
710    [director, siegel, really, impressed, film, st...          1
18858  [gabe, ryan, frankie, thomas, gets, reform, sc...          1

[10000 rows x 2 columns]

In [26]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [27]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [28]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [29]:
df['review']=df['review'].apply(stem_words)

In [30]:
df

                                                  review  sentiment
24045  [accord, quit, bizarr, movi, lot, humor, say, ...          1
6619   [peopl, vote, meager, 1, movi, say, guy, matur...          1
21179  [written, stephen, king, treatment, solid, sto...          0
5611   [idea, produc, shield, tri, result, speak, shi...          0
14729  [saw, film, awhil, back, work, trailer, film, ...          0
...                                                  ...        ...
39536  [show, like, watch, someon, train, someday, ho...          0
15903  [children, movi, movi, like, bad, acid, trip, ...          0
27413  [tumbl, doll, flesh, tamakichi, anaru, japanes...          1
710    [director, siegel, realli, impress, film, star...          1
18858  [gabe, ryan, franki, thoma, get, reform, schoo...          1

[10000 rows x 2 columns]

In [31]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [32]:
df['review']=df['review'].apply(join_back)

In [33]:
df['review']

24045    accord quit bizarr movi lot humor say scari fu...
6619     peopl vote meager 1 movi say guy matur enough ...
21179    written stephen king treatment solid stori fil...
5611     idea produc shield tri result speak shield pra...
14729    saw film awhil back work trailer film product ...
                               ...
39536    show like watch someon train someday host show...
15903    children movi movi like bad acid trip kid age ...
27413    tumbl doll flesh tamakichi anaru japanes shock...
710      director siegel realli impress film starkli sh...
18858    gabe ryan franki thoma get reform school goe b...
Name: review, Length: 10000, dtype: object

In [34]:
X=df.iloc[:,0:1].values

In [35]:
X.shape

(10000, 1)

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)

In [37]:
X=cv.fit_transform(df['review']).toarray()

In [38]:
X.shape

(10000, 2500)

In [39]:
X[0].mean()

np.float64(0.0092)

In [40]:
y=df.iloc[:,-1].values

In [41]:
y.shape

(10000,)

In [42]:
# X,y
# Training set
# Test Set(Already know the result)

In [43]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [44]:
X_train.shape

(8000, 2500)

In [45]:
X_test.shape

(2000, 2500)

In [46]:
y_train.shape

(8000,)

In [47]:
y_test.shape

(2000,)

In [48]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [49]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [50]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [51]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [52]:
y_test.shape

(2000,)

In [53]:
y_pred1.shape

(2000,)

In [54]:
from sklearn.metrics import accuracy_score

In [55]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.739
Multinomial 0.843
Bernaulli 0.847